### ISSUE TITLE
> > text: Receive 0.14 TON + 100 USDT

### ISSUE THREAD

**Issue by Hamed1370m** [ton-blockchain/wallet-contract#183] opened 2024-11-08 20:11 UTC
> > text: Receive 0.14 TON + 100 USDT

_Originally posted by @LuCaSiNo40 in https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451737911_

**Comment by Hamed1370m** [comment] 2024-11-08 20:13
UQCIZh-syryRUHb2GfgpEFA9aRvj3KWyWgg81noOjyY
cb_n3

Im wallet tonkepper

**Comment by Hamed1370m** [comment] 2024-11-08 20:17
> > text: Receive 0.14 TON + 100 USDT

**Comment by Hamed1370m** [comment] 2024-11-08 20:17
[https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451290138](url)

**Comment by Mina2889** [comment] 2024-11-08 22:24
maingit-branch--m-main-<BRANCH>-git-fetch-origin-git-branch--u-origin/<BRANCH>-<BRANCH>-git-remote-set-head-origin--a

در تاریخ جمعه ۸ نوامبر ۲۰۲۴،‏ ۱۱:۴۸ ب.ظ Hamed1370m ***@***.***>
نوشت:

**Comment by Mina2889** [comment] 2024-11-08 22:55
> ```
>       > > text: Receive 0.14 TON + 100 USDT
> ```

**Comment by Mina2889** [comment] 2024-11-08 22:56
Duplicate of #

**Comment by Mina2889** [comment] 2024-11-08 22:56
> > text: Receive 0.14 TON + 100 USDT

**Comment by Mina2889** [comment] 2024-11-08 22:56
https://github.com/ton-blockchain/wallet-contract/issues/183#issuecomment-2465872570

**Closed** 2024-11-09 02:16 UTC

**Comment by Kawser13011991** [comment] 2024-11-09 02:43
> ```
>           > > text: Receive 0.14 TON + 100 USDT
> ```
> 
> _Originally posted by @LuCaSiNo40 in [ton-blockchain/TEPs#119 (comment)](https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451737911)_

#183

**Comment by pamparon** [comment] 2024-11-09 02:45
Yes

**Comment by Przem-SS** [comment] 2024-11-17 13:19
> ```
>           > > text: Receive 0.14 TON + 100 USDT
> ```
> 
> _Originally posted by @LuCaSiNo40 in [ton-blockchain/TEPs#119 (comment)](https://github.com/ton-blockchain/TEPs/issues/119#issuecomment-2451737911)_

          > > text: Receive 0.14 TON + 100 USDT

**Comment by Przem-SS** [comment] 2024-11-25 09:43
Receive 0.14 TON + 100 USDT #183

**Comment by pamparon** [comment] 2024-11-25 11:49
What?
